[phases.setup]
commands = [
  "echo 'Setting up the environment...'"
]

[phases.build]
commands = [
  "echo 'Building the project...'"
]

[phases.start]
commands = [
  "echo 'Starting the application...'"
]

[variables]
PORT = "4000"