[phases.setup]
commands = [
  "echo 'Setting up the environment...'",
  "curl -fsSL https://deb.nodesource.com/setup_16.x | bash -",
  "apt-get install -y nodejs"
]

[phases.build]
commands = [
  "cd frontend && npm install && npm run build",
  "cd backend && npm install"
]

[variables]
PORT = "4000"