[phases.setup]
commands = [
  "echo 'Setting up the environment...'",
  "apt-get update",  # Actualizar los paquetes
  "curl -fsSL https://deb.nodesource.com/setup_16.x | bash -",
  "apt-get install -y nodejs",
  "node -v",  # Verificar la instalación de Node.js
  "npm -v"    # Verificar la instalación de npm
]

[phases.build]
commands = [
  "cd frontend && npm install && npm run build",
  "cd backend && npm install"
]

[phases.start]
commands = [
  "cd backend && npm start"
]

[variables]
PORT = "4000"